In [2]:
# Loading data from variable path
import numpy as np

In [3]:
data_file='/content/KAG_Conversion_Data.csv'
data=np.genfromtxt(data_file,delimiter=',',encoding=None,skip_header=1,dtype=str)
data_int=np.genfromtxt(data_file,delimiter=',',encoding=None,skip_header=1,dtype=int)
print(data)
print(data_int)

[['708746' '916' '103916' ... '1.429999948' '2' '1']
 ['708749' '916' '103917' ... '1.820000023' '2' '0']
 ['708771' '916' '103920' ... '0' '1' '0']
 ...
 ['1314412' '1178' '179979' ... '40.28999949' '2' '0']
 ['1314414' '1178' '179981' ... '198.7100005' '8' '2']
 ['1314415' '1178' '179982' ... '165.6099987' '5' '2']]
[[ 708746     916  103916 ...      -1       2       1]
 [ 708749     916  103917 ...      -1       2       0]
 [ 708771     916  103920 ...       0       1       0]
 ...
 [1314412    1178  179979 ...      -1       2       0]
 [1314414    1178  179981 ...      -1       8       2]
 [1314415    1178  179982 ...      -1       5       2]]


In [4]:
#Determining the unique ad campaigns from the given data
unique_ids=np.unique(data[: ,1])

In [5]:
unique_ids

array(['1178', '916', '936'], dtype='<U11')

**Thus We have 3 unique ID campaigns**

**Determining the number of times each unique campaign was ran**

In [6]:
len(data[data[:,1]=='916'])

54

In [7]:
len(data[data[:,1]=='1178'])

625

In [8]:
len(data[data[:,1]=='936'])

464

**Determining the different age groups targeted through these ad campaign as fillows;**

In [9]:
age_groups=data[:,3]
age_groups

array(['30-34', '30-34', '30-34', ..., '45-49', '45-49', '45-49'],
      dtype='<U11')

**Deternining average, minimum and maximum amount spend on the ads**

In [10]:
ads_amount=data_int[:,8]
ads_amount

array([-1, -1,  0, ..., -1, -1, -1])

In [ ]:
#Average amount spend on ads

In [11]:
avg_amount=ads_amount.mean()

In [12]:
avg_amount

-0.7681539807524059

In [13]:
round(avg_amount,2)

-0.77

In [ ]:
# Minimum amount spent on ads

In [21]:
min_amount=ads_amount.min()
min_amount

-1

In [22]:
max_amount=ads_amount.max()
max_amount

57

In [ ]:
# ID of ads with maximum number of clicks

In [14]:
max_clicks=np.max(data_int[:,7])

In [15]:
int(max_clicks)

421

In [16]:
int(data_int[:,0][data_int[:,7]==421])

1121814

In [17]:
int(data_int[:,10][data_int[:,7]==421])

13

In [ ]:
# Number of people who bought the product of seeing the add with most clicks

In [18]:
max_purchases=np.max(data_int[:,10])

In [19]:
max_purchases

21

In [ ]:
# Details of product with maximum number of purchase

In [20]:
data_int[data_int[:,10]==21]

array([[1121104,    1178,  144533,      -1,      -1,      16, 2080666,
            202,      -1,      40,      21]])